### ISSUE TITLE
CommandError !  Can anyone help me Thanks !

### ISSUE THREAD

**Issue by jeremy55662004** [openedx-unsupported/edx-analytics-pipeline#80]
When i was installing edx-analytics-dashboard on how to install and run the analytics backend locally there was an error below when i had a command  (make validate) :
![screenshot from 2015-03-21 01 29 10](https://cloud.githubusercontent.com/assets/9279378/6757199/35400cd6-cf6a-11e4-9d2d-489d7e53febd.png)

I have no idea how to fix it !  If someone can give me a tip and i will be grateful.

Thanks !!

by jeremy

**Comment by sssso** [comment]
i got same error!!!
